## where to store your database, default is your system data directory
## mac: ~/Library/Application Support/com.elliehuxtable.atuin/history.db
## linux: ~/.local/share/atuin/history.db
# db_path = "~/.history.db"

## where to store your encryption key, default is your system data directory
# key_path = "~/.key"

## where to store your auth session token, default is your system data directory
# session_path = "~/.key"

## date format used, either "us" or "uk"
# dialect = "uk" 								

## enable or disable automatic sync
# auto_sync = true

## enable or disable automatic update checks
update_check = false

## how often to sync history. note that this is only triggered when a command 
## is ran, so sync intervals may well be longer
## set it to 0 to sync after every command
# sync_frequency = "5m"

## address of the sync server
# sync_address = "https://api.atuin.sh"

## which search mode to use
## possible values: prefix, fulltext, fuzzy
search_mode = "fuzzy"

# the default filter to use when searching
filter_mode = "directory"

## which style to use
## possible values: auto, full, compact
style = "compact"

# invert the UI. Put the search bar at the top
invert = "true"

# set the maximum number of lines the interface should take up (0 is all available space)
inline_height = 30

# configure whether or not to show a preview of the selected command
show_preview = false

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
# exit_mode = "return-original"

# The initial keymap mode of the interactive search
keymap_mode = "vim-insert"

history_filter = [
  "^ls",
  "^cd$",
  "^cd ..$",
  "^btop",
  "^hx$",
  "^z $"
]
