# theme = "aoInherit"
theme = "doom_acario_dark_inherit"
# theme = "bogsterInherit"
#theme = "bogster"

[editor]
cursorline = true
#auto-format = false
color-modes = true
#auto-pairs = false
idle-timeout = 200
soft-wrap.enable = true
popup-border = "all"
line-number = "relative"
bufferline = "multiple"
end-of-line-diagnostics = "warning"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
separator = "/"
left = ["mode", "spinner", "file-name", "file-type", "file-encoding", "read-only-indicator"]
center = ["diagnostics", "selections"]
right = ["position", "separator", "total-line-numbers", "separator", "position-percentage"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = ":"

[editor.inline-diagnostics]
cursor-line = "error"

# [editor.smart-tab]
# supersede-menu = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
C-r = ":config-reload"
J = ["select_line_below"]
K = ["select_line_above"]
H = ["select_mode", "goto_line_start", "exit_select_mode"]
L = ["select_mode", "goto_line_end", "exit_select_mode"]
C-J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
F5 = [":sh cargo run"]
d = "delete_selection_noyank"
c = "change_selection_noyank"
# tab = ":toggle line-number absolute relative"

[keys.insert]
A-l = ["move_char_right"]
A-h = ["move_char_left"]
A-k = ["move_visual_line_up"]
A-j = ["move_visual_line_down"]

[keys.select]
H = ["goto_line_start"]
J = ["select_line_below"]
K = ["select_line_above"]
L = ["goto_line_end"]

