theme = "bogsterInherit"
#theme = "bogster"

[editor]
cursorline = true
#auto-format = false
color-modes = true
#auto-pairs = false
idle-timeout = 200
soft-wrap.enable = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
separator = "/"
left = ["mode", "spinner", "file-name", "file-type", "file-encoding"]
center = ["diagnostics", "selections"]
right = ["position", "separator", "total-line-numbers", "separator", "position-percentage"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = ":"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
C-r = ":config-reload"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
F5 = [":sh cargo run"]
tab = ":toggle line-number absolute relative"

[keys.insert]
j = { k = "normal_mode" }
